// front-react/src/App.jsx
import { useState } from 'react'
import ky from 'ky'
import './App.css'

function App() {
  const [posts, setPosts] = useState([])

  async function retrievePosts () {
    const payload = await ky.get('http://localhost:8000/api/posts').json();
    setPosts(payload);
  }

  return (
    <div className="App">
      <header className="App-header">
          <button type="button" onClick={retrievePosts}>Load posts</button>
      </header>
      <main>
        {posts && posts.map((post) => (
          <div key={post.id}>
            <h2>{post.title}</h2>
            <div>{post.content}</div>
            <time>Créé : {post.createdAt}</time>
            <time>Modifié : {post.updatedAt}</time>
          </div>
        ))}
      </main>
    </div>
  )
}

export default App

// front-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  posts: any = [];

  constructor (private http: HttpClient) {}

  retrievePosts() {
    this.http.get('http://localhost:8000/api/posts').subscribe((data: any) => {
      this.posts = data['hydra:member'] as any;
    })
  }
}

<div>
  <button (click)="retrievePosts()">Load posts</button>
  <div *ngFor="let post of posts">
    <h2>{{ post.title }}</h2>
    <div>{{ post.content }}</div>
    <time>{{ post.createdAt }}</time>
    <time>{{ post.updatedAt }}</time>
  </div>
</div>
